# Generated by Django 3.2 on 2021-06-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=70)),
                ('lastName', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('gender', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
            ],
        ),
    ]
