# Generated by Django 3.2 on 2021-06-27 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productDescription', models.CharField(max_length=900)),
                ('profileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='purchaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('quantity', models.BigIntegerField()),
                ('totalAmount', models.BigIntegerField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.productmodel')),
            ],
        ),
    ]
