# Generated by Django 3.2 on 2021-07-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0003_salesdetailsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileNumber', models.IntegerField(blank=True, null=True)),
                ('GSTno', models.IntegerField(blank=True, null=True)),
                ('profileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.registermodel')),
            ],
        ),
    ]
