# Generated by Django 3.2 on 2021-07-09 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0004_customermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='CGST',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchasemodel',
            name='IGST',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchasemodel',
            name='customerId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.customermodel'),
        ),
        migrations.AddField(
            model_name='purchasemodel',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
