# Generated by Django 3.2 on 2021-07-09 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0005_auto_20210709_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
