# Generated by Django 3.2 on 2021-07-09 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0006_alter_purchasemodel_purchasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 18, 0, 23, 26115)),
        ),
    ]
