# Generated by Django 3.2 on 2021-07-09 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0011_alter_purchasemodel_purchasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='GSTno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 9, 22, 27, 31, 14598), null=True),
        ),
    ]
