# Generated by Django 3.2 on 2021-07-09 17:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0013_auto_20210709_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='customerId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='inventoryApp.customermodel'),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 9, 22, 40, 59, 784566), null=True),
        ),
    ]
