# Generated by Django 3.2 on 2021-07-09 17:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0014_auto_20210709_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='customerId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.customermodel'),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.productmodel'),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 9, 23, 24, 59, 794182), null=True),
        ),
    ]
