# Generated by Django 3.2 on 2021-07-09 17:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0015_auto_20210709_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='CGST',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='IGST',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='customerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.customermodel'),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 9, 23, 29, 33, 602544), null=True),
        ),
    ]
