# Generated by Django 3.2 on 2021-07-10 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0016_auto_20210709_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='productDescription',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 10, 17, 32, 33, 385839), null=True),
        ),
    ]
