# Generated by Django 3.2 on 2021-07-11 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0017_auto_20210710_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='taxableAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 11, 12, 34, 26, 566677), null=True),
        ),
    ]
