# Generated by Django 3.2 on 2021-07-22 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0019_auto_20210711_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 22, 12, 54, 54, 500075), null=True),
        ),
        migrations.CreateModel(
            name='stockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('purchaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.purchasemodel')),
            ],
        ),
    ]
