# Generated by Django 3.2 on 2021-07-28 18:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0020_auto_20210722_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdetailsmodel',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='salesdetailsmodel',
            name='total',
        ),
        migrations.AddField(
            model_name='salesdetailsmodel',
            name='CGST',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesdetailsmodel',
            name='IGST',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesdetailsmodel',
            name='customerId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.customermodel'),
        ),
        migrations.AddField(
            model_name='salesdetailsmodel',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salesdetailsmodel',
            name='sellDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 23, 37, 45, 195282)),
        ),
        migrations.AddField(
            model_name='salesdetailsmodel',
            name='stockId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.stockmodel'),
        ),
        migrations.AddField(
            model_name='salesdetailsmodel',
            name='taxableAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesdetailsmodel',
            name='totalAmount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 28, 23, 37, 45, 195282), null=True),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='invoice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
