# Generated by Django 3.2 on 2021-07-28 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0021_auto_20210728_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 28, 23, 40, 56, 292465), null=True),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='customerId',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.customermodel'),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='sellDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 28, 23, 40, 56, 292464)),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='stockId',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.stockmodel'),
        ),
    ]
