# Generated by Django 3.2 on 2021-07-28 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0025_auto_20210728_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 28, 23, 46, 7, 303995), null=True),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='CGST',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='IGST',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='invoice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='sellDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='taxableAmount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='totalAmount',
            field=models.BigIntegerField(),
        ),
    ]
