# Generated by Django 3.2 on 2021-07-28 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0032_alter_purchasemodel_purchasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 28, 23, 58, 33, 643483), null=True),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='customerId',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.customermodel'),
        ),
        migrations.AlterField(
            model_name='salesdetailsmodel',
            name='stockId',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.stockmodel'),
        ),
    ]
