# Generated by Django 3.2 on 2021-07-28 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0041_alter_purchasemodel_purchasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 29, 0, 47, 53, 239456), null=True),
        ),
    ]
