# Generated by Django 3.2 on 2021-07-29 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0048_alter_purchasemodel_purchasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 29, 15, 33, 55, 601402), null=True),
        ),
        migrations.DeleteModel(
            name='salesdetailsmodel',
        ),
    ]
