# Generated by Django 3.2 on 2021-08-19 10:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0050_auto_20210729_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 19, 15, 58, 29, 399589), null=True),
        ),
        migrations.CreateModel(
            name='returnPurchaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseReturnDate', models.DateTimeField()),
                ('returnQuantity', models.IntegerField()),
                ('custName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.customermodel')),
                ('purchaseReturn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.sellmodel')),
            ],
        ),
    ]
