# Generated by Django 3.2 on 2021-08-19 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0051_auto_20210819_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 19, 16, 1, 49, 108621), null=True),
        ),
    ]
