# Generated by Django 3.2 on 2021-08-19 10:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0053_auto_20210819_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 19, 16, 29, 38, 969558), null=True),
        ),
        migrations.AlterField(
            model_name='returnpurchasemodel',
            name='purchaseReturnId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.stockmodel'),
        ),
    ]
