# Generated by Django 3.2 on 2021-08-27 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0054_auto_20210819_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 27, 16, 11, 0, 66143), null=True),
        ),
        migrations.CreateModel(
            name='returnSellModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellReturnDate', models.DateTimeField()),
                ('sellReturnInvoice', models.CharField(max_length=100)),
                ('sellReturnQuantity', models.IntegerField()),
                ('sellReturnProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.productmodel')),
            ],
        ),
    ]
