# Generated by Django 3.2 on 2021-08-29 08:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0055_auto_20210827_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 29, 14, 29, 52, 45915), null=True),
        ),
        migrations.AlterField(
            model_name='returnsellmodel',
            name='sellReturnInvoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventoryApp.sellmodel'),
        ),
    ]
