# Generated by Django 3.2 on 2021-08-29 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryApp', '0056_auto_20210829_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnsellmodel',
            old_name='sellReturnInvoice',
            new_name='sellReturnSellId',
        ),
        migrations.AlterField(
            model_name='purchasemodel',
            name='purchaseDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 29, 14, 36, 3, 810056), null=True),
        ),
    ]
